server:
  port: 8083

spring:
  application:
    name: PAYMENT-SERVICE

  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost